### ISSUE TITLE
Set wallpaper as an explicit argument

### ISSUE THREAD

**Issue by dantempla** [Kharacternyk/pacwall#12]
Not an issue, but a quality of life suggestion.
I wasn't expecting the tool to set the wallpaper right away without explicitly declaring it. Maybe add a new argument like `-w` or `-wallpaper` to declare explicitly setting it as a wallpaper as well.

**Comment by Kharacternyk** [comment]
I see it better vice versa: to have a flag to forbid the wallpaper setting. The script is called pac***wall*** and I want it to do everything it can unless it was constrained by a user.

**Comment by dantempla** [comment]
As long as there is a kind of switch to turn it on and off, sure why not.
