### ISSUE TITLE
Image size changes when there are more circles

### ISSUE THREAD

**Issue by ChiDal** [Kharacternyk/pacwall#14]
When there are a few too many packages, the size of the image changes and does not follow screen size (neither does it follow if size is explicitly given using args). This makes it like this:
![pacwall](https://user-images.githubusercontent.com/36493671/77464890-c35d9680-6dff-11ea-9c3e-139a9494a08d.png)

Since the aspect ratio is broken, the image stretches/zooms in on the background which makes it pixelated and ugly:
![Screenshot from 2020-03-24 23-11-49](https://user-images.githubusercontent.com/36493671/77465075-0455ab00-6e00-11ea-8b61-ce77c3760dc5.png)

Or maybe a recent commit broke it and it has nothing to do with the number of packages.

**Comment by ChiDal** [comment]
The flags in the troubleshooting section downsize the whole image ie the image size becomes 400x500 or something

**Comment by ChiDal** [comment]
Desirable behaviour: the blank space increases but image size is always equal to screen size

**Comment by ChiDal** [comment]
Confirmed: a commit broke it, a previous version of the script is fine

**Comment by Kharacternyk** [comment]
What does the desirable image look like? The default value for `-r` flag is 1, you may try `-r 0.8` to make the image slightly smaller.

**Comment by Kharacternyk** [comment]
Your first picture looks like one that `twopi` outputs, without resizing. Maybe the `imagemagick` piece of code is broken now?

**Comment by ChiDal** [comment]
Lemme nuke it and see?

**Comment by ChiDal** [comment]
> What does the desirable image look like? The default value for `-r` flag is 1, you may try `-r 0.8` to make the image slightly smaller.

Desirable image generated by earlier version:
![pacwall](https://user-images.githubusercontent.com/36493671/77468745-ee4ae900-6e05-11ea-9fc9-9b0788ca7159.png)
Also tried r=0.8

**Comment by ChiDal** [comment]
> Your first picture looks like one that `twopi` outputs, without resizing. Maybe the `imagemagick` piece of code is broken now?

The earlier version also had imagemagick:
![image](https://user-images.githubusercontent.com/36493671/77468961-4550be00-6e06-11ea-95e8-537e2ede7cd0.png)

**Comment by Kharacternyk** [comment]
I fixed it (?) in be1d606.

**Comment by ChiDal** [comment]
Yes
