### ISSUE TITLE
DE integration.

### ISSUE THREAD

**Issue by Kharacternyk** [Kharacternyk/pacwall#16]
We put the generated wallpaper in `~/.local/share/wallpapers`, but, if the DE isn't GNOME, the wallpapers there are unresized. If the DE doesn't provide an option to center the image and use a solid color outside, setting the wallpaper from GUI is broken.

Possibilities:

- Strictly require `imagemagick`.
- Check whether `imagemagick` is installed and resize the image if it is.
- Provide support for DEs separately. As of now large effort has been put only in GNOME support.
- Pretend there is no problem.

**Comment by Kharacternyk** [comment]
Related: #14.

**Comment by ChiDal** [comment]
Since the script is pacWALL and not pacIMAGE, we can strictly require imagemagick
(installed size 9.7 MB)
![image](https://user-images.githubusercontent.com/36493671/77535120-f486a700-6e91-11ea-93af-97f4a8c866b9.png)

**Comment by ChiDal** [comment]
Also for many users, imagemagick is already installed as a dependency of something else anyway

**Comment by Kharacternyk** [comment]
I don't like `imagemagick` as a mandatory dependency because *I don't need it*. If one doesn't use a DE, one shouldn't be told to install `imagemagick`.

**Comment by ChiDal** [comment]
Make 2 branches - DE and WM?

**Comment by Kharacternyk** [comment]
The difference would be just that in one version we check for GNOME to resize and in other we don't. Maybe a command line flag like `-D` to force resizing will do fine?

**Comment by ChiDal** [comment]
You need imagemagick for all DEs

**Comment by ChiDal** [comment]
There is no point in copying unresized images to `XDGOUT` because they are meant to be used through the GUI

**Comment by Kharacternyk** [comment]
Then maybe copying to `XDGOUT` should be a part of "DE mode" that is activated via `-D`.

**Comment by Kharacternyk** [comment]
I guess b93a4e2 closes this.
