### ISSUE TITLE
"sudo mode"

### ISSUE THREAD

**Issue by RuijieYu** [Kharacternyk/pacwall#20]
Suggestion to add a "global mode". I am trying to add a pacman hook but was unable to do so because I was under sudo. (And the hook's syntax to use execv instead of execvp makes it harder).

**Comment by Kharacternyk** [comment]
I have removed the mode because of lack of documentation (d804e5). Reopening this.

**Comment by Kharacternyk** [comment]
v2.* doesn't suffer from the issue, closing it.
