### ISSUE TITLE
Script hangs when I try to run it

### ISSUE THREAD

**Issue by cafeTechne** [Kharacternyk/pacwall#24]
Ubuntu 18.04 here. 

When I try to run the script it never finishes running. What more info could I give you to help you trace the issue?

**Comment by Kharacternyk** [comment]
That's weird. What is the last line of the output? Maybe you have a lot of packages installed? `twopi` is slow when is feed a large graph to render.

I used 18.04 for testing. The script worked fine, though the system was rather small (minimal install).

**Comment by cafeTechne** [comment]
There is no output. Granted, I didn't let it run longer than 20-30 minutes. I'll re-run it and give it a few hours as a good faith attempt. I'll run it with the -x flag and see what we get!

**Comment by cafeTechne** [comment]
nvm! User issue! I didn't close the string I was passing in as the final argument! I'm so sorry to waste your time!

**Comment by Kharacternyk** [comment]
No output? Then the problem doesn't have anything to do with the number of packages, it hangs before even start generating anything.

**Comment by Kharacternyk** [comment]
Ah, ok:)
