### ISSUE TITLE
aur packages not necessarily "foreign"

### ISSUE THREAD

**Issue by RuijieYu** [Kharacternyk/pacwall#28]
As the title says. e8da45bac1750874fe845d200e16bea7e91dca1c introduces a different type of node for AUR packages, but the list is obtained from `pacman -Qm` according to source. Some aur helpers put packages in a local repository that pacman recognizes, and therefore no aur packages would be reported despite having them installed. 

A possible addition is to enable a switch with argument as repository name, and use `paclist <repo>` to obtain the list installed through said repository. We can optionally allow multiple said switches to include multiple repositories recognized as aur.

**Comment by Kharacternyk** [comment]
These switches are a great idea. Not just AUR, we can highlight packages from *core*, *extra* and *community* as well.

**Comment by Kharacternyk** [comment]
And *multilib*!

**Comment by Kharacternyk** [comment]
Could you test the changes (db15c68 and 74b407e)? Like this `pacwall aur_repo:color`.

BTW, the algorithm now renders the graph a bit differently. The count of nodes and edges is the same though, I've checked.

**Comment by RuijieYu** [comment]
I don’t have much time right now to test (I’m still in college); will do in the weekend if I have time.

**Comment by RuijieYu** [comment]
I have some time to test now. In the meantime, we can also add support to `pywal` here by using some custom syntax for selecting colors from within `pywal`.

**Comment by RuijieYu** [comment]
Things look pretty good!

- `pacwall repo1:color1 repo2:color2` and `pacwall repo2:color2 repo1:color1` generate images that look the same (didn't bother to check hash). 
- `pacwall repo:color1 repo:color2` correctly shows `color2` as the node color.

**Comment by Kharacternyk** [comment]
So, closing this?

> I have some time to test now. In the meantime, we can also add support to `pywal` here by using some custom syntax for selecting colors from within `pywal`.

Pywal prints hex values of colors when choosing a theme. One can just feed the values to pacwall.
