### ISSUE TITLE
Sanity check for cmdopts.

### ISSUE THREAD

**Issue by RuijieYu** [Kharacternyk/pacwall#29]
Using `pacman -r ROOT` does not work. See the image for the result when I say `pacman -DWr libalpm`. It seems that the image is the same with other packages such as `git` or `linux`. 

![2020-04-09T20:03:14,167280658-04:00](https://user-images.githubusercontent.com/12377059/78950573-2ce6d180-7a9d-11ea-9043-95ee853d3e7a.png)

**Comment by RuijieYu** [comment]
When I checked the source code I noticed that `-r` is the ranksep, whereas `-c` is custom root, which means my original issue was invalid. However, it is surprising that the script would run at all; maybe add a sanity check for the arguments?

**Comment by Kharacternyk** [comment]
I'm surprised that `twopi` doesn't complain when gets `-Granksep=libalpm`. We need to check ourselves, I do agree.

BTW, `-c` stands for `center`, that's how I chose it.

**Comment by Kharacternyk** [comment]
This issue doesn't apply to v2.*
