### ISSUE TITLE
Background image support.

### ISSUE THREAD

**Issue by Kharacternyk** [Kharacternyk/pacwall#32]
Should be easily accomplished via `imagemagick`.

**Comment by DaLemonBoi** [comment]
> Should be easily accomplished via `imagemagick`.

Can you explain this more? I'm not familiar with imagemagick.

**Comment by Kharacternyk** [comment]
`imagemagick` is a tool for image modification and creation. It has [composite](https://imagemagick.org/script/composite.php) command that overlays two images. We could make the background of the graph transparent and lay it onto the user-specified image using the `composite` command. This is what I meant by "Background image support".

**Comment by Kharacternyk** [comment]
This can be achieved via a custom hook in v2.*
