### ISSUE TITLE
How to make a full screen wallpaper??

### ISSUE THREAD

**Issue by sleeperzjf** [Kharacternyk/pacwall#38]
I install `pacwall` from `AUR`, and how can I generate a `1920x1080` wallpaper in my filesystem?
I'm using `X`, the instruction in `readme` says:
![image](https://user-images.githubusercontent.com/65698607/86910879-f4629c80-c14c-11ea-9f51-845b653058e3.png)
Does it mean that I can't do that?

**Comment by Kharacternyk** [comment]
It should work out of the box on Xorg. Do you have `feh` or `hsetroot` installed? They are listed as optional dependencies in AUR, hence they are not installed automatically. Pacwall needs one of these two programs to be able to set the wallpaper.

**Comment by sleeperzjf** [comment]
I'm aware of that and I can set the wallpaper. What I mean is how can I
generate a local image on my computer.

**Comment by Kharacternyk** [comment]
The generated image is always cropped to the graph. There is a hack though: if you pass `-D` and have both `xorg-xdpyinfo` and `imagemagick` installed, then the resized image will be in `~/.local/share/wallpapers/pacwall/`.

**Comment by sleeperzjf** [comment]
I run `pacwall -b "#282a36" -D -S "1920x1080"` and the image generated
is still in my home directory, but it is the right size now.
Thank you!

**Comment by Kharacternyk** [comment]
This indeed works, turns out I forgot the way the things are done if `-D` is passed. Maybe it would make sense to respect `-S` even if `-D` isn't set, but this is for another issue. Glad I could help.
