### ISSUE TITLE
Portage support?

### ISSUE THREAD

**Issue by Bfgeshka** [Kharacternyk/pacwall#4]
Should be very doable. If you do not want to do it then maybe someone else will.

**Comment by Kharacternyk** [comment]
That would be another project I think (***gent***wall?). I leave the issue here though, PRs are welcome.

**Comment by ChiDal** [comment]
I think you need to do it yourself @Bfgeshka . I don't think anyone would be willing to install Gentoo (which ig compiling tons of stuff) just for this.

**Comment by Kharacternyk** [comment]
Gentoo is fun in its own way, but not when your CPU is Intel Core 2 Duo from 2005:)

If I buy one day a bit better hardware and manage to install Gentoo on it, then porting pacwall will be the first thing for me to do.

**Comment by PitcherTear22** [comment]
Same here, stuck on this until I get a new HDD for my desktop (Seagayte failed)
![specs](https://user-images.githubusercontent.com/36493671/78179407-abfe5900-7450-11ea-9d29-6a8fcff56888.png)

**Comment by Bfgeshka** [comment]
@PitcherTear22 i would if i could, but my knowlegde of python is extremely limited, and there would be needed some parsing changes aside from pacman invokation replacements.

**Comment by adtyanair** [comment]
I can work on this if nobody else is already on it

**Comment by Kharacternyk** [comment]
@adtyanair This would be superb. I've looked at the forks graph and it seems that no one else works on it.

**Comment by adtyanair** [comment]
I was trying to figure out what the script is actually doing and it looks like I need some help. 
in the function `generate_graph_pactree()`,  can you tell me what's the use of the `!` and `[arrowhead=crow]` added to some package names?

**Comment by Kharacternyk** [comment]
There are virtual packages on Arch. For example, `ttf-font` isn't really a package, but some packages like `ttf-ibm-plex` *provide* `ttf-font`. Another example is `libconfig.so=11-64` which is provided by `libconfig`.

Pacwall replaces `>=`, `=` and the like in the names of such virtual packages with `!`. Also, it changes the direction of the arrow: `[arrowhead=crow]`.

**Comment by Kharacternyk** [comment]
Closing as v1 already has Gentoo support and v2 likely won't have it.
