### ISSUE TITLE
Ubuntu 20.04 HELP

### ISSUE THREAD

**Issue by GiorgChr** [Kharacternyk/pacwall#40]
I am using Ubuntu 20.04 with Regolith. When i run `./pacwall.sh -D` it just uses the regular ubuntu background. Am i missing something? Is there anything i can do to generate a wallpaper? The output is 
`Using pactree to generate the graph

./pacwall.sh: line 44: pacman: command not found

./pacwall.sh: line 37: pacman: command not found

./pacwall.sh: line 37: pacman: command not found

./pacwall.sh: line 37: pacman: command not found

./pacwall.sh: line 37: pacman: command not found

./pacwall.sh: line 98: checkupdates: command not found

Using gsettings to set the wallpaper

Using hsetroot to set the wallpaper

Using feh to set the wallpaper`

**Comment by theRippedPug** [comment]
I too am a Ubuntu user and want to use this amazing utility. It looks like you need an arch-based system to get this to work. 
Is it hard to port the pacman-based logic to ubuntu/debian's APT package manager?

**Comment by GiorgChr** [comment]
> I too am a Ubuntu user and want to use this amazing utility. It looks like you need an arch-based system to get this to work. 
> Is it possible to port the pacman-based logic to ubuntu/debian's APT package manager?

I'm pretty sure it can work. I saw a post by the person who made the pacwall on the ubuntu subreddit.

**Comment by Kharacternyk** [comment]
> I saw a post by the person who made the pacwall on the ubuntu subreddit.

Yep, it was me. I'm sorry, but I've already dropped Ubuntu (and Debian) support. There are a couple of reasons:

* There are a lot of preinstalled packages on Ubuntu, hence the image is very cluttered.

* I don't have an Ubuntu or Debian machine anymore, hence it's difficult for me to port all the features.

**Comment by GiorgChr** [comment]
> > I saw a post by the person who made the pacwall on the ubuntu subreddit.
> 
> Yep, it was me. I'm sorry, but I've already dropped Ubuntu (and Debian) support. There are a couple of reasons:
> 
> * There are a lot of preinstalled packages on Ubuntu, hence the image is very cluttered.
> 
> * I don't have an Ubuntu or Debian machine anymore, hence it's difficult for me to port all the features.
> 

I understand. Is it possible though to send me the old files to try to come up with something my self? I will not share it with on github it's just for me to create a nice desktop. Or perhaps, if it's easier to tell me what to change in the script. Thanks

**Comment by Kharacternyk** [comment]
The change was done in 8d0bed9 commit, you can see the apt integration code there.

**Comment by GiorgChr** [comment]
Thank you very much.
