### ISSUE TITLE
syntax error in line 1691 near '['

### ISSUE THREAD

**Issue by user18130814200115-2** [Kharacternyk/pacwall#41]
Exact command run:
`pacwall -b "#2e3440" -s "#d8dee950" -d "#bf616a" -e "#88c0d0" -p "#a3be8c" -f "#b48ead" -u "#ebcb8b" -y "#eceff4" -x "#a3be8c" -z "#ebcb8b"`

**Comment by Kharacternyk** [comment]
You misuse the `-x` and `-z` flags. Here is some relevant excerpts from the help message:

> [ -x ORPHAN_NODE_OUTLINE ]
> [ -z OUTDATED_NODE_OUTLINE ]

> If OUTLINE value is bigger than 1, then OUTLINE-1 additional circles are drawn around the corresponding packages.
