### ISSUE TITLE
Package manager detection

### ISSUE THREAD

**Issue by adtyanair** [Kharacternyk/pacwall#43]
identify package manager automatically, without the use of flags specified by the user. (like -V for voidlinux)
(discussed in #42 )

**Comment by Kharacternyk** [comment]
Linking some relevant excerpts:

> for setups like yours *(Arch with xbps installed)* and distributions like Bedrock Linux, with multiple package managers, there should be some way to choose which to use, if this is further expanded to support other package managers too

> package manager checking order *(current)*: pacman -> xbps -> emerge

**Comment by Kharacternyk** [comment]
In v2.* only Arch is supported. Sorry.
