### ISSUE TITLE
Add/Change Coloring Option for Foreign Packages in Version 2

### ISSUE THREAD

**Issue by pixel1138** [Kharacternyk/pacwall#51]
Is it possible to set a different coloring for Foreign packages in version 2 like it was in version 1?  If not, is it possible for the functionality to be added back in?

**Comment by Kharacternyk** [comment]
Sorry for the delay.

It is not currently possible, but I'm working on adding this back in. Most likely it won't be in the form of "a package is foreign or native", but in the richer form of "a package is from the repository X" where a package that isn't found in any repos is foreign.

**Comment by pixel1138** [comment]
I apologize for the delay in replying. 

Thank you for for the response, and I understand that it will take time.  That sounds like a very nice enhancement!

**Comment by Kharacternyk** [comment]
Checkout v2.1. Foreign packages are green by default now. See the description of the `attributes.package.repository` setting in the README for more info.

**Comment by pixel1138** [comment]
Thank you! I most certainly will!
