### ISSUE TITLE
Non-orphan packages marked as orphan

### ISSUE THREAD

**Issue by DAMO238** [Kharacternyk/pacwall#52]
Running `pacman -Qqtd` yields no results, so there are no orphans installed. I then check one of the supposed orphans that pacwall is showing and it has a install reason as 'as a dependency'. This is when it shows that it is only an optional dependency, which is sufficient for pacman to not say it is an orphan, but pacwall only looks at required dependencies, leading to a discrepancy between pacwall and pacman. For example, I have cuda installed and gdb as an optional dependency for it marked as a dependency. Pacwall shows gdb as an orphan when it is not and pacman does not show it as an orphan.

**Comment by Kharacternyk** [comment]
I've done it this way deliberately. As I understand it, if a package has been installed as a direct dependency and isn't directly required anymore, then it's an orphan. One should either remove it or, if it's a desired optional dependency, mark it as explicitly installed.

You are not wrong either, though. It's just that I consider the output of `pacman -Qttd` orphans and you define orphans as the output of `pacman -Qtd`. Furthermore, I've just checked the Arch Wiki and it shares your opinion on this, saying that `pacman -Qtd` lists *true* orphans.

I can split the `attributes.package.orphan` setting into one for true orphans and another for "optional" orphans. Would it be an acceptable solution?

**Comment by DAMO238** [comment]
Thank you for explaining your methodology! I think splitting the `attributes.package.orphan` setting would be the best of both worlds.

**Comment by Kharacternyk** [comment]
Sorry for the delay.

I have added the `attributes.package.unneeded` setting. It is empty by default and contains attributes that are applied to "the `pacman -Qtd` packages" on top of `attributes.package.orphan`. So if you want to highlight *only* true orphans, set `attributes.package.orphan` to the empty value and `attributes.package.unneeded` to the highlighting you like.
