### ISSUE TITLE
Version 2.3 has not been pushed to AUR

### ISSUE THREAD

**Issue by deimosian** [Kharacternyk/pacwall#56]
I'm not sure if there's a reason for it or if it's just slipped your mind, but figured I'd poke here since it's been quite some time since 2.3 was released here.

**Comment by Kharacternyk** [comment]
New versions of `-git` packages don't need to be pushed to the AUR. The latest commit is automatically fetched each time the package is installed.

**Comment by deimosian** [comment]
I didn't know that, that's nice. 

However, shouldn't at least the version number in AUR be updated at least so that it gets updated when someone runs yay -Syu or w/e?

**Comment by Kharacternyk** [comment]
I don't know much about AUR helpers, maybe you're right. I'll push it soon.

**Comment by deimosian** [comment]
I don't know that much about them either, but I can confirm that running upgrades through my chosen helper, YAY, does not upgrade it, I've still got 2.2. I assume a reinstall would do it, but I'll wait to test upgrade again after you push.

**Comment by Kharacternyk** [comment]
I've updated the AUR info.

**Comment by deimosian** [comment]
```
:: Searching databases for updates...
:: Searching AUR for updates...
:: 1 Packages to upgrade.
1  aur/pacwall-git  2.2.r8.geb6baaf-1 -> 2.3.r3.gca02590-1
```

Can confirm that flagged it for upgrade by yay.

**Comment by Kharacternyk** [comment]
TIL that I should bump versions of my packages in the AUR more often:)
