### ISSUE TITLE
with wayland

### ISSUE THREAD

**Issue by JoaoVitorMendes** [Kharacternyk/pacwall#64]
is there a way to use it with wayland? Because I'm trying to use it here and I'm not having success

**Comment by Kharacternyk** [comment]
There are instructions for Sway in the README with an important caveat:
> If you use Sway, you must run systemctl --user import-environment SWAYLOCK by the time the systemd units are triggered. They will fail otherwise.

I think the other WMs and DEs on Wayland haven't been really tested. `pacwall

**Comment by Kharacternyk** [comment]
`

**Comment by JoaoVitorMendes** [comment]
I use Hyprland, but I tried some, I tried using the sway hook and it didn't work

**Comment by Kharacternyk** [comment]
Hyprland should support `swaybg`, so let's try it:
* Verify that `pacwall` has generated an image at `~/.cache/pacwall/pacwall.png`.
* Install `swaybg`.
* Run `swaybg -i ~/.cache/pacwall/pacwall.png`.
* If the above command works, you can use it as a wallpaper hook: `hook: "swaybg -i '$W'"`.

Please let me know whether these steps work for you.

**Comment by JoaoVitorMendes** [comment]
yes, I'm off work, when it arrives I'll test it! thanks <3

**Comment by JoaoVitorMendes** [comment]
Thank you very much <3, it worked like a glove <3
