### ISSUE TITLE
Incompatible with Pacman 6.1

### ISSUE THREAD

**Issue by deimosian** [Kharacternyk/pacwall#67]
Getting the following when trying to run pacwall after upgrading today:

`pacwall: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory`

Seems to be related to a pacman update, Yay had same issue and already fixed. https://github.com/Jguer/yay/issues/2393

**Comment by Kharacternyk** [comment]
Have you tried rebuilding/reinstalling the `pacwall-git` package? It should pick up the new version of `libalpm`.

**Comment by deimosian** [comment]
That fixed it, didn't get done automagically because Yay didn't consider it in need of updating.

**Comment by Kharacternyk** [comment]
> Yay didn't consider it in need of updating
I think this issue affects all `-git` packages that don't bump versions explicitly.

**Comment by deimosian** [comment]
It doesn't affect all of them for me, like today I ran an upgrade and it did the `oh-my-zsh-git` update `r7165.0fed36688-1  -> latest-commit` even though in the AUR it's still listed as `r6192.be4a95297-1`

It and other `-git` packages that get updated are listed as `devel/$package-git` instead of `aur/$package` in the list. I think it doesn't recognize `pacwall-git` as a git/devel package for some reason.
